FROM hub.siu.edu.ar:5005/siu/expedientes/arai-usuarios/idm:v3.0.8

COPY src/SIU/AraiUsuarios/Util/Varios.php /usr/local/app/core/src/SIU/AraiUsuarios/Util/Varios.php
#COPY src/core/src/SIU/AraiUsuarios/Backends/Helpers/UsuarioHelperLdap.php /usr/local/app/core/src/SIU/AraiUsuarios/Backends/Helpers/UsuarioHelperLdap.php
#COPY src/core/src/SIU/AraiUsuarios/Definitions/Ldap.yml /usr/local/app/core/src/SIU/AraiUsuarios/Definitions/Ldap.yml
#COPY src/idm/php/operaciones/usuarios/ci_usuarios_listado.php /usr/local/app/idm/php/operaciones/usuarios/ci_usuarios_listado.php